### PR TITLE
New rule: prefer-readonly-type-declaration

### PR DESCRIPTION
**Pull request by RebeccaStevens**
Re #153

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
@jonaskello I think this implementation addresses all the issues and is pretty much ready to go.

I copied over the upstream utils that we are waiting on for now. It can easily be stripped out later.

There are a few changes I want to make to those utils but I'll submit upstream PRs to try and address those.

Let me know what you think.

**Comment by jonaskello** [comment]
Regarding the name of the rule, I'm thinking maybe `prefer-readonly-declaration` would suffice to keep it shorter. However the longer name is more correct so I'm not sure about this.

Regarding the new `aliases` option I think we need to perhaps discuss this a bit further and think about use-cases and overlaps with the `ignorePattern` option. If the intent of the rule is to require that every declaration is readonly save a few exceptional cases I think the ignorePattern already solves this. Or is there some use case where the `aliases` optional would be needed to have full coverage for this use-case?

**Comment by jonaskello** [comment]
If I understand correctly this rule will no longer check readonly declarations of function parameters but instead rely on the  `@typescript-eslint/prefer-readonly-parameter-types` for that, which is good because we don't need to overlap what is already present in the offical lib. I saw this was noted in the deprecation notes. I think it should probably be noted in the docs for this rule too that this is an intentional omission.

**Comment by RebeccaStevens** [comment]
### Rule name

I think having the word `type` in the name makes it more clear that the rule is for types and thus a TypeScript specific rule. This also makes it clear that rule doesn't check other declarations (such as function declarations or variable declarations) (to be clear, it does check type declarations on these other declarations).

### Aliases option

This option is more powerful than the `ignorePattern` option but it only applies to type aliases and interfaces.
The main thing it allows for is checking whether a deeply nested property is allowed to be mutable or not based on the alias's/interface's name. The `ignorePattern` option only checks shallowly against the property's name.

It's probably also worth noting that this new rule is now more strict than the previous one. Type aliases/interfaces are also checked as whole now, rather than the individual elements being individually checked. (The individual elements are also check but only for the purpose of the fixer - this is simply because implementing a fixer for the whole type would be more difficult and we already had the code to do it this way. I may implement the other way in the future.)

### Function parameters

> this rule will no longer check readonly declarations of function parameters but instead rely on the @typescript-eslint/prefer-readonly-parameter-types for that

That's actually not correct. This rule will still check function parameters just like before if they use a type literal (as opposed to a type reference).

For example:

```ts
// Will fail to both "prefer-readonly-type-declaration" and "@typescript-eslint/prefer-readonly-parameter-types"
function foo(param: { bar: number }) {}
```

```ts
// Will fail to "prefer-readonly-type-declaration"
type Param = { bar: number };

// Will fail only to "@typescript-eslint/prefer-readonly-parameter-types"
function foo(param: Param) {}
```

The main reason I kept this behavior was so that we can still implement our fixer (to add `readonly` modifiers to the properties and change `Array` to `ReadonlyArray`, etc).

**Comment by jonaskello** [comment]
> ### Rule name

Yes, it is definitely a tradeoff between brevity and clarity. I have no strong opinion on this so let's go with the longer name.

> ### Aliases option

I will have to think about this a little more but just a quick question on terminology for now. If we write eg. `type MyTuple = [number, string]` I think that `MyTupe` is referred to as a "type alias". When you say "...only applies to type aliases..." I think you mean only type aliases for object types? Or is the intent to also check other aliases, eg. if you alias an array or tuple?

> ### Function parameters

Ah, I did not catch that, thanks for clarifying. Good point about the fixer, don't want to be without that :-).

**Comment by RebeccaStevens** [comment]
`type MyTuple = [number, string]` will be checked by this rule and flagged.

Things like `type MyType = typeof myValue;` will also be checked.

**Comment by RebeccaStevens** [comment]
Oh, I should point out that the this new rule also supports `Readonly<T>`.

**Comment by jonaskello** [comment]
Yes, `type MyTuple = [number, string]` will be flagged by the old rule too I think? What I'm trying to figure out is if the intent behind the `aliases` option to be able to do something like this:

```ts
type MutableTuple = [string, number] // This is is ignored using `alias` option? 
type MyTuple = [string, number] // This is flagged
```

or if it is more geared towards something like this:

```ts
type MutableObj = { x: number, y: {z: string}  }; // This is is ignored using `alias` option? 
type MyObj = { x: number, y: string }; //  This is flagged
```

or the intent is to support both these cases?

**Comment by RebeccaStevens** [comment]
To support both.

**Comment by jonaskello** [comment]
Just to clairfy a bit about the `ignorePattern` option. The intent of this rule was to mimic how some functional-first languages work.  Everything is immutable except where explicitly marked immutable. AFAIK these languages provides two escape hatches to make things mutable (eg. for performance reasons). The first one is to make a variable mutable, we can look at this [example for F#](https://www.tutorialspoint.com/fsharp/fsharp_mutable_data.htm):

```f#
let x = 15
x <- 15 // this will not work
let mutable y = 10
y <- 15 // this will work since y is marked as mutable
```

The equivalent in js/ts is `const` vs `let` so here we use the `prefer-const` rule with `ignorePattern` escape hatch to name the variable something to emulate the `mutable` modifier.

```ts
let x = 15 // this will not work becuase of prefer-const rule
let mutableY = 10 // this will work since y is named as mutable and is ignored by prefer-const rule
```

The second escape hatch these languages provide is using the same modifier but on fields within a record type. The F# example link as above contians this example:

```f#
type studentData =
   { ID : int;
      mutable IsRegistered : bool;
      mutable RegisteredText : string; }
```

In this case `ID` is immutable but `IsRegistered` and `RegisteredText` are mutable since they are marked with the mutable modifier. The same thing in typescript with `prefer-readonly-type` rule and `ignorePattern` option:

```f#
type studentData =
   { readonly ID : number;
      MutableIsRegistered : boolean;
      MutableRegisteredText : string; }
```

AFAIK the functional languages the rule is trying to emulate does not have an escape hatch that allows a whole type to be marked as mutable. You can of course mark every field with the modifier, and the equivalent in typescript with the rule would then be to prefix all field names with mutable. My concern is that I'm not sure it's a good idea to provide escape hatches for our rules that do not exist in functional-first languages.

**Comment by jonaskello** [comment]
OTOH, typescript is really different from F#/ocaml/reasonml etc. so it might make sense to have more escape options :-).

I guess the aliases option that enable whole type mutability would be like having the mutable modifier on the type keywork in F# etc. Something like this:
 
```f#
type mutable studentData =
   { ID : int;
      IsRegistered : bool;
      RegisteredText : string; }
```

I don't think this syntax exists in F# or other ML based languages but if it did I guess it would make all fields of the type `studentData` mutable. Not sure why they avoid this syntax in those languages.

**Comment by jonaskello** [comment]
I'm trying to think of use-cases for the `aliases` option. I'm mainly thinking from the perspective of making immutable the default and then having some way to ignore checking where it is not wanted. I've come up with the following so far:

```ts
// This works already with ignorePattern set to "^[mM]utable"
export const mutableNumbersArray: number[] = [1, 2, 3];
export type Foo = { mutableBar: number };
export type MutableNumbersArray = number[];
export const numbersArray: MutableNumbersArray = [1, 2, 3];
// This does not work with ignorePattern
export type MutableFoo = { bar: number };
```

So the case I have found so far is to make a whole object type alias as mutable. Are there more cases?

**Comment by RebeccaStevens** [comment]
Fully functional programming languages such as [Haskell](https://www.haskell.org/) don't even have the concept of mutability. Although F# allows for allowing for mutability, this is just an escape hatch into non-functional programming.

I agree that we should try to support the same style of marking properties as mutable that F# does (via a naming convention); but we shouldn't simply lock into this being the end all. And yeah, as TypeScript is a very different language to F# and the like, enabling a way to mark an entire type as mutable seems like it should be supported - especially when working with 3rd-party libraries. In fact, our code is relying on this to work with ESLint [see type MutableRuleTesterTests in this commit](https://github.com/jonaskello/eslint-plugin-functional/pull/259/commits/b1b92e8413fa9a835a97f1af5e3ac3d9a65321d9)

**Comment by RebeccaStevens** [comment]
I just reworked the `aliases` options to make them more simple but just as powerful.

Now instead of the `aliases` object, there are these 3 options: `ignoreAliasPatterns`, `readonlyAliasPatterns` and `mutableAliasPatterns`.

**Comment by RebeccaStevens** [comment]
Also note that

```ts
type Foo = { mutableBar: number };
```

**Comment by RebeccaStevens** [comment]
Also note that with the default config and `ignorePattern` set to `"^[mM]utable"`, the following would actually be a violation.

```ts
// { "ignorePattern": "^[mM]utable" }
type Foo = { mutableBar: number };
//   ^^^ Error - name suggests the type should not be mutable.
```

To fix this the type's name would have to be renamed:

```ts
// { "ignorePattern": "^[mM]utable" }
type MutableFoo = { mutableBar: number };
//                  ^^^^^^^^^^ No error but the mutable prefix has no effect.
```

Or the `readonlyAliasPatterns` would need to configure differently. The option can be turned off by setting it to `[]` and this would restore the previous behavior of `prefer-readonly-type`.

```ts
// { "ignorePattern": "^[mM]utable", readonlyAliasPatterns: [] }
type Foo = { mutableBar: number }; // Works just like it did with `prefer-readonly-type`.
```

**Comment by jonaskello** [comment]
I think the new options are a good improvement! I'm thinking now about how these new options (`ignoreAliasPatterns`, `readonlyAliasPatterns` and `mutableAliasPatterns`) interact and/or overlap with the existing `ignorePattern` option.

If we only wanted to add the possibility to avoid checking fields of whole types, I guess the simplest way would be to modify the  `igonorePattern` option so it also checks against the type name for object types/interfaces in addition to field name. That would allow _ignoring_ full types/interfaces without having to prefix each field name. However if you choose to prefix with `Mutable` as ignoring pattern so you get eg. `MutablePerson` as a type name, I can see how it would seem logical that it should not only be ignored but also enforced to be fully mutable. In that case the rule would actually work in the opposite way of it's name, not prefering readonly declarations but instead unprefering them :-). For my part ignoring would be enough but as long as there is no strange interaction/overlap between ignoring omission of readonly vs enforcing omission of readonly I guess it could not hurt to have this functionality (disregarding any maintenance burden for it).

Is the intention of the `ignoreAliasPatterns` to simply ignore omissions of readonly for all fields in object types? If this is the case perhaps we could just roll that functionality into the existing `ignorePattern` option?

I'm still unsure about the use-case for the `readonlyAliasPatterns`. Is the intention to check that all fields for object types with certain type names have readonly modifiers for all fields? If so is that not what the rule is doing by default for all type names?

**Comment by RebeccaStevens** [comment]
So to clarify, we aren't checking for full mutability, only full immutability and not full immutability. So the following would be perfectly accepted:

```ts
type MutablePerson = {
  name: string;
  readonly dateOfBirth: Date;
}
```

However if `name` also had a `readonly` modifier, the rule would error with:
`"Mutable types should not be fully readonly. If this type is supposed to me readonly, mark it as so."`

The reason I added `ignoreAliasPatterns` was as a work around for a use case I was having with the previous options implementation. I haven't actually checked whether the new implementation has the same issue or not. The use case was allowing for was having a `Mutable<T>` type without this type triggering the rule.

```ts
type Mutable<T> = {
  -readonly[P in keyof T]: T[P]
};
```

The `readonlyAliasPatterns` option is used to detect what type aliases should be fully readonly. This defaults to `^(?!I?Mutable).+$` (all type not prefixed with "Mutable" or "IMutable"). This options allows users to change the requirements. For example, users may only want to enforce that only types prefixed with "Readonly" are deeply readonly. I've included some other [example in the rule's docs](https://github.com/jonaskello/eslint-plugin-functional/blob/prefer-readonly-type-declaration/docs/rules/prefer-readonly-type-declaration.md#readonlyaliaspatterns-and-mutablealiaspatterns).

**Pull request closed without merging**
