### PR TITLE
v5.0.0

### LINKED ISSUE #32: Prefer Readonly<T> over readonly keyword
Transferred from jonaskello/tslint-immutable#58

### LINKED ISSUE #51: [prefer-readonly-type] Support Readonly<T>
Support the following case (at the moment `functional/prefer-readonly-type` gets emitted):

```TS
type MyType = Readonly<{ a: string, b: number }>;
```

This is a prerequisite for #32 (which is about a fixer to `Readonly<T>` if I understand it correctly); but the validation can implemented before.

### LINKED ISSUE #150: [prefer-readonly-type] doesn't catch mutable records
`prefer-readonly-type` catches this:

```ts
type Foo = {
  [K in string]: string;
};
```

but not this, which is equivalent:

```ts
type Bar = Record<string, string>;
```

It would be great if `prefer-readonly-type` could be extended to catch `Record` (but _not_ `Readonly<Record<...>>`), and even better if it had a fixer that replaced the above with:

```ts
type Bar = Readonly<Record<string, string>>;
```

### LINKED ISSUE #153: [prefer-readonly-type] Rework this rule.
### Function Return Types

The return type of functions shouldn't be enforced to be immutable (by default) (this behavior can currently be turned on with the `allowMutableReturnType` option).

Following from this, the rule [`@typescript-eslint/explicit-function-return-type`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) should no longer be a recommend external rule.

#### Enforce Mutable Return Types

If the return type has to immutable then something very non-functional is going on. What happens to the data after it is returned by a function should be of no concern to the function itself. Mutable return types are more compatible with 3rd-party non-function code as readonly types can not be given as mutable types in TypeScript (while mutable types can be given as either a mutable or readonly type).

An option to enforce this behaviour should be added to the rule (whether this is the default behavior or not is currently undecided).

### Type Aliases

Often a mutable type needs to be aliased. This rule should not trigger an error when a mutable type is aliased (by default), only when the mutable type is used.

Care will be need to be taken when implementing this to keep performance good - we don't want to reevaluate every instance of type alias usage to check whether it's mutable or not.

### New Rule

As this is such a large change to the current implementation of rule, it's probably best to instead create this change as a new rule and deprecate the current rule. Any suggestions on a new rule name?

### LINKED ISSUE #384: Autofix on TypeScript mapped types with `-readonly` cause syntax error
# Bug Report

I have the following code:

```ts
export type Writable<T> = {
  -readonly [K in keyof T]: T[K];
};
```

ESLint reports "functional/prefer-readonly-type" rule and an option to "--fix" it.

## Expected behavior

Autofix should remove `-`:

```ts
export type Writable<T> = {
  readonly [K in keyof T]: T[K];
};
```

## Actual behavior

Autofix creates a syntax error:

```ts
export type Writable<T> = { readonly
  -readonly [K in keyof T]: T[K];
};
```

## Steps to reproduce

ESLint config:

```json5
{
  // ...
  plugins: [
    // ...
    'functional',
    // ...
  ],
  extends: [
    // ...
    "plugin:functional/external-recommended",
    "plugin:functional/recommended",
    "plugin:functional/no-object-orientation",
    "plugin:functional/no-statements",
    "plugin:functional/no-exceptions",
    "plugin:functional/currying",
    "plugin:functional/stylistic",
    // ...
  ],
// ...
}
```

## Proposed changes

Either disable autofix for `-readonly`, or hande it properly.

See https://github.com/microsoft/TypeScript/pull/21919

### LINKED ISSUE #387: Autofix for `functional/prefer-readonly-type` produces confusing formatting
# Bug Report

Autofix for `functional/prefer-readonly-type` on a mapped type like the following inserts `readonly` on a wrong line:

```ts
let a: {
  [B in 'c']: 'd';
};
```

## Expected behavior

```ts
let a: {
  readonly [B in 'c']: 'd';
};
```

## Actual behavior

```ts
let a: { readonly
  [B in 'c']: 'd';
};
```

## Proposed changes

Put `readonly` on the correct line.

## Additional information

Related to #384

### PR DESCRIPTION
**Pull request by RebeccaStevens**
Closes #32
Closes #51
Closes #150
Closes #153
Closes #384 
Closes #387 
Fixes: #468
Fixes: #500

## Install

`npm i -D eslint-plugin-functional@next`

`yarn add -D eslint-plugin-functional@next`

### CODE REVIEW

**Comment by jonaskello** [comment]
We have quite many projects relying mainly on `prefer-readonly-type` to keep things immutable. Since it will be deprecated with 5.0 I'm mostly concerned about the migration path for these projects. My thinking was that I should had time to document a migration path to get the same level of immutability using the new rules but unfortunately I have not had time to do so yet.

Perhaps one way would be some simple comparison table that references `prefer-readonly-type` and the replacement.

**Comment by jonaskello** [comment]
For reference the rules we use are in [this repo](https://github.com/dividab/eslint-config-divid) and more specifically [here](https://github.com/dividab/eslint-config-divid/blob/master/src/rules/functional/no-mutations.js) regarding the `prefer-readonly-type` rule. The options we use are `{ allowLocalMutation: true, ignorePattern: "^[mM]utable" }`.

**Comment by jonaskello** [comment]
I thyink the main job of `prefer-readonly-type` is basically to ensure that `readonly` modifier is used in all places where typescript supports them. With the new rules I guess this job would be split between other rules so perhaps that could be put in a table in order to find the migration path. This is a incomplete example of that:

| Type           | Typescript readonly suppport                          | Old rule | New rule |
|----------------|----------------------------------------|----------|----------|
| Array          | ReadonlyArray<T> or readonly attribute |    `prefer-readonly-type`       |          |
| Tuple          | readonly attribute                     |      `prefer-readonly-type`     |          |
| Object         | readonly attribute                     |     `prefer-readonly-type`      |          |
| Class property | readonly attribute                     |    `prefer-readonly-type`       |          |

**Comment by RebeccaStevens** [comment]
Here's how the new setup will work:

```ts
const globalVar: { foo: string } = ...; // No error as this doesn't get checked.
```

```ts
type MutableFoo = { foo: string }; // No error as declared as mutable
const globalVar: MutableFoo = ...; // No error
```

```ts
type Foo = { foo: string };  // Error as not immutable
const globalVar: Foo = ...;  // No error.
```

With the new rules, there is currently no way to check inline type declarations.
I guess a new rule should be added to check such declarations but it's not a rule I would use myself as I tend to alias everything.

**Comment by jonaskello** [comment]
I had a second look now and my understanding is that `prefer-immutable-types` will now enforce all readonly types that typescript offers, in all locations in the code, except for `type` declarations which is instead handled by `type-declaration-immutableness`. Would that be correct?

**Comment by RebeccaStevens** [comment]
Yeah, that's right (interfaces are also covered by `type-declaration-immutableness`)

**Comment by RebeccaStevens** [comment]
@jonaskello We already to release this?

**Comment by jonaskello** [comment]
Since the main rule we rely on is being deprecated in this release I feel I need to verify a bit more before I feel comfortable with this release. It's just time constraints that is keeping me from doing it. I'll try to find some time in the very near future, like hopefully later today :-)

One question I can think of right now is about the having `prefer-immutable-types` and `type-declaration-immutableness` as separate rules. As far as I understand they both verify that you have used the available compile time readonly declarations that typescript supports, although in different places. Since `prefer-immutable-types` has options for specifying where to check for readonly (parameters, returnTypes, variables), it seems like `type-declaration-immutableness` could just be more options on `prefer-immutable-types` at this point (types, interfaces). Perhaps there is a reason to keep them separate that I am not seeing?

**Comment by RebeccaStevens** [comment]
They probably could be merged into one, but I think it would be best to keep them separate.
The main reason for this is that `prefer-immutable-types` is about flagging inline mutable types (when used for with variables or functions). While 
`type-declaration-immutability` is about flagging inconsistencies in type alias and interfaces.

`type-declaration-immutability` doesn't necessarily enforce aliases to be immutable, but rather will apply rules that enforce a min and/or max immutability. With the default "strict" options, it will simply enforce that any alias not prefixed with "Mutable" will have to be immutable.

**Comment by jonaskello** [comment]
I've started some testing. Took me a while to find why `no-this-expression` was not working anymore. I guess it is because of this:

> rename rules to make them plural.
> rename a bunch of options too.

Perhaps the change notes could be more explicit of which rules changed :-)

**Comment by RebeccaStevens** [comment]
Yeah, I was planning on doing manual write of the release notes for 5.0 rather than using the automated ones. I was just going to use the automated ones for the betas.

**Comment by jonaskello** [comment]
When using this config:

```js
  rules: {
    "functional/prefer-immutable-types": ["error", { variables: { allowInFunctions: true } }],
  },
```

I get the error:

```
Oops! Something went wrong! :(

ESLint: 8.8.0

Error: .eslintrc.js:
        Configuration for rule "functional/prefer-immutable-types" is invalid:
        Value {"allowInFunctions":true} should NOT have additional properties.
        Value {"allowInFunctions":true} should be string,number,boolean.
        Value {"allowInFunctions":true} should be equal to one of the allowed values.
        Value {"allowInFunctions":true} should match exactly one schema in oneOf.
````

I'm trying to replace the config below for the old rule with the new one, what would be the correct config?

```
  rules: {
    "functional/prefer-readonly-type": ["error", { allowLocalMutation: true, ignorePattern: "^[mM]utable" }],
  },
```

**Comment by jonaskello** [comment]
The docs for `prefer-immutable-types` mentions [here](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/prefer-immutable-types.md#default-options) that the default is `allowLocalMutation: false,` but the docs above does not list `allowLocalMutation` as an available option. I guess this is just a leftover from the old rule? The correct config should be `allowLocalMutation: true` under the variables section instead?

**Comment by RebeccaStevens** [comment]
It's supposed to be `ignoreInFunctions`

**Comment by RebeccaStevens** [comment]
The docs have both, `allowInFunctions` needs to be changed in the docs.

**Comment by RebeccaStevens** [comment]
`allowLocalMutation` is left over and should be removed.

I'll make these fixes now.

**Comment by jonaskello** [comment]
Ah, that makes sense. Everything else was named `ignoreXXX` so I was going to suggest that `allowInFunctions` should be renamed to `ignoreInFunctions` but then it is already so :-)

**Comment by jonaskello** [comment]
It seems the quick-fix for `prefer-immutable-types` is not working as in `perfer-readonly-type`. We use this quick-fix a lot to save typing the readonly stuff by hand.

image


image

**Comment by RebeccaStevens** [comment]
The fixer has been removed for now.
It's something I want to being back, but I haven't prioritized it.

The reason why it has been removed is because the new fixer will need to work a bit different. For example, with the code you provided above, how should the type be made immutable? It will depend on the `enforcement` level that is configured. With, `ReadonlyShallow` or `ReadonlyDeep` it can simply be changed to `readonly string[]` but for `Immutable`, there is no nicely built in way to make an array immutable. Once (/if) https://github.com/sindresorhus/type-fest/pull/479 is merged, `ReadonlyDeep<string[]>` would work. But as that type comes from a library, does the fixer need to make sure that type is imported? To support other type libraries, we'd also need to make this fix configurable.

This is all do-able but I've put in the do later camp for now.

**Comment by jonaskello** [comment]
Given this code:

```ts
interface Foo {
  readonly bar: string;
}

function testtwo(quantity: string): ReadonlyArray<Foo> {
  return [{ bar: "" }];
}
```

and this config:

```js
module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module",
    project: "./tsconfig.json",
  },
  plugins: ["functional", "@typescript-eslint", "import"],
  rules: {
    "functional/prefer-immutable-types": ["error", { variables: { ignoreInFunctions: true } }],
  },
};
```

I get this error:

```
$ eslint ./src/**/*.ts{,x} --ext .js,.ts,.tsx -f visualstudio
xxxx.ts(9,35): error functional/prefer-immutable-types : Return type should have an immutability of at least "Immutable" (actual: "ReadonlyDeep").
```

If I change it to return just `Foo` instead of `ReadonlyArray<Foo>` it works. I would expect both to work?

**Comment by RebeccaStevens** [comment]
`ReadonlyArray<T>` is not immutable as the methods on the array can be changed. You'll want to lower the `enforcement` to `ReadonlyDeep`.

**Comment by RebeccaStevens** [comment]
These are the definitions of the different enforcement levels: https://github.com/RebeccaStevens/is-immutable-type#definitions

> `Immutable`: Everything is deeply read only and nothing can be modified.
> `ReadonlyDeep`: The data is deeply immutable but methods are not.
> `ReadonlyShallow`: The data is shallowly immutable, but at least one deep value is not.
> `Mutable`: The data is shallowly mutable.

**Comment by jonaskello** [comment]
Would setting `ReadonlyDeep` on global level give the exact same enforcement as `prefer-readonly-types` in all places? Currently I'm getting "6559 problems" when switching to `prefer-immutable-types` in the code base I'm currently working on. So I'm looking for options that would let me migrate without having to change everything :-).

**Comment by jonaskello** [comment]
Regarding the quick-fix, for us it would be enough that it fixes the same cases as `prefer-readonly-types` did. Perhaps we can detect if the current config allows for a simple fix and then allow for quick-fix?

**Comment by RebeccaStevens** [comment]
I'll probably work on the fixer in stages, the first stage will be adding those simple fixes.

**Comment by jonaskello** [comment]
This code:

```ts
export type Program<TReturn> = Generator<unknown, TReturn, unknown>;

function partialCall4<TProgramArray extends Array<Program<unknown>>>(
  ...args: [...TProgramArray]
): ExtractProgramArrayReturnTypeTuple<TProgramArray> {
  return args as any;
}

type ExtractProgramArrayReturnTypeTuple<T extends ReadonlyArray<Program<any>>> = {
  [K in keyof T]: T[K] extends Program<infer V> ? V : never;
};
```

Gives the errors:

```
$ eslint ./src/**/*.ts{,x} --ext .js,.ts,.tsx -f visualstudio

Oops! Something went wrong! :(

ESLint: 8.25.0

TypeError: Cannot read properties of undefined (reading 'flags')
Occurred while linting /home/jonkel/code/experiment/estest/src/a.ts:3
Rule: "functional/prefer-immutable-types"
    at Object.isUnionType (/home/jonkel/code/experiment/estest/node_modules/tsutils/typeguard/2.8/type.js:70:18)
    at unionTypeParts (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:116:19)
    at isPropertyReadonlyInType (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:200:21)
    at isReadonlyPropertyFromMappedType (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:252:12)
    at /home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:229:21
    at someTypePart (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:125:52)
    at isReadonlyPropertyIntersection (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:222:12)
    at Object.isPropertyReadonlyInType (/home/jonkel/code/experiment/estest/node_modules/tsutils/util/type.js:211:43)
    at objectImmutability (/home/jonkel/code/experiment/estest/node_modules/is-immutable-type/dist/index.cjs:290:25)
    at calculateTypeImmutability (/home/jonkel/code/experiment/estest/node_modules/is-immutable-type/dist/index.cjs:264:16)
```

The settings:

```js
module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module",
    project: "./tsconfig.json",
  },
  plugins: ["functional", "@typescript-eslint", "import"],
  rules: {
    // "functional/prefer-readonly-type": ["error", { allowLocalMutation: true, ignorePattern: "^[mM]utable" }],
    "functional/prefer-immutable-types": [
      "error",
      { enforcement: "ReadonlyDeep", variables: { ignoreInFunctions: true } },
    ],
  },
};
```

**Comment by RebeccaStevens** [comment]
Looks like a bug with tsutils

**Comment by RebeccaStevens** [comment]
https://github.com/ajafff/tsutils/issues/147

**Comment by RebeccaStevens** [comment]
@jonaskello I've update some of the logic and dependencies, do you want to retest and see if you are still having that issue?

**Comment by RebeccaStevens** [comment]
@jonaskello I've just pushed a new version of `is-immutable-type` (v1.2.1) that removes the reliance on `tsutils` and patches the function bug.
You should be able to run `beta.10` now without issue. Just make sure you are using the latest version of `is-immutable-type` (The easiest way to ensure this is to delete your `yarn.lock` file then re-install the deps).

**Comment by jonaskello** [comment]
Yes, I was able to continue the testing now. I ran into a situation with this code (simplified as much as I could):

```
export type DoubleSegment = {
  readonly type: "Double";
};

export type BoxDef = {
  readonly type: "BoxDef";
};

export const doubleSegment = (boxes: BoxDef): DoubleSegment => ({
  type: "Double",
});
```

It gives this linting error:

```
/home/jonkel/code/github/jonaskello/eslint-functional-test/src/index.ts(9,31): error functional/prefer-immutable-types : Parameter should have an immutability of at least "ReadonlyDeep" (actual: "Mutable").
/home/jonkel/code/github/jonaskello/eslint-functional-test/src/index.ts(9,45): error functional/prefer-immutable-types : Return type should have an immutability of at least "ReadonlyDeep" (actual: "Mutable").

2 problems
```

I think these types should satisfy the `ReadonlyDeep` rule or am I missing something? I updated the code on the [test repo](https://github.com/jonaskello/eslint-functional-test) with the code above.

**Comment by RebeccaStevens** [comment]
Yeah, there shouldn't be any errors there.
I've been able to recreate the issue locally, but I can't seem to write a test that recreates it. Any test I write seems to have the correct behavior so I'm not sure where the problem is coming from. I'll continue to investigate.

**Comment by RebeccaStevens** [comment]
And now I can't seem to recreate the issue at all.
Maybe there was an issue with dependencies...

Try deleting `node_modules` and `yarn.lock`; then try again.

**Comment by RebeccaStevens** [comment]
I think I've found the problem. I think beta.10 was just beta.9 re-released instead of having the needed updates. I'll rerelease it as beta.11

**Comment by jonaskello** [comment]
Yes, now it works :-). Sounds like that was a hard one to figure out, good work finding it!

So I've continued testing on a code base that previously used `prefer-readonly-type` and now I am down to 1317 problems using these settings (was something like 6000 before):

```js
  rules: {
    // "functional/prefer-readonly-type": ["error", { allowLocalMutation: true, ignorePattern: "^[mM]utable" }],
    "functional/prefer-immutable-types": [
      "error",
      {
        enforcement: "ReadonlyShallow",
        variables: { ignoreInFunctions: true },
        parameters: { ignoreInferredTypes: true },
        returnTypes: { ignoreInferredTypes: true },
      },
    ],
    "functional/type-declaration-immutability": [
      "error",
      { rules: [{ identifiers: "^(?!I?Mutable).+", immutability: "ReadonlyShallow" }] },
    ],
```

The new rules seems to be much more comprehensive which is great! However it also poses an issue for smooth migration of existing code bases using `prefer-readonly-type`.  Some examples issues that the new rules cover that the old one did not is this:

```ts
export interface Vec2 {
    x: number;
    y: number;
}

export function frameLinesXY(
  min: Vec2, // new rules gives error but old does not
): ReadonlyArray<Mesh> {
//

const foo = { bar: "bar" };
type Foo = typeof foo; // new rules gives error but old does not

}
```

For `prefer-readonly-type` this was OK but with `prefer-immutable-types` it does not, which is correct because `Vec2` is a mutable parameter. And `foo` should be declares `as const` in order to be immutable. For smooth migration it would of course be preferable to have options to use this old behaviour, perhaps sometlhing like `ignoreCustomTypes`. But for just using the new rules for new projects I don't think such an option would make sense so I'm not sure if it is something worth pursuing.

**Comment by jonaskello** [comment]
One thing I noticed from a usability standpoint is that the rule options seem currently to be bit different between the two new rules. For example it is called `enforcement: "ReadonlyShallow"` vs. `immutability: "ReadonlyShallow" `. It would be nice to have both rules configured in the same manner. For usability I think it would be even better to merge them into one rule but perhaps the options are too different for that?

Another thing I noticed is that the code base had comments like `/* eslint-disable functional/prefer-readonly-type */` to disable the rule for certain files. First I thought I could just do a search and replace with but since there are now to separate rules this is not as simple as that. This could also be a reason for merging the rules (to be able to disable both with a single comment).

**Comment by RebeccaStevens** [comment]
> perhaps sometlhing like `ignoreCustomTypes`.

`ignoreInferredTypes` should work for those cases you pointed out

**Comment by RebeccaStevens** [comment]
> `enforcement: "ReadonlyShallow"` vs. `immutability: "ReadonlyShallow" `

The reason for the two different names is because they do something a bit different to each other.

`enforcement` for `prefer-immutable-types` is stating that the immutability must be **at least** this.
While `immutability` for `type-declaration-immutability` is stating that this is the level of immutability we'll be testing against. It doesn't necessarily have to be at least this, it's dependent on the `comparator` specified.

**Comment by RebeccaStevens** [comment]
> `/* eslint-disable functional/prefer-readonly-type */`

Could you not just replace it with:

`/* eslint-disable functional/prefer-immutable-types, functional/type-declaration-immutability */`

**Comment by jonaskello** [comment]
Yes, of course, why did I not think of that :-). So did two more things:

- Replaced `/* eslint-disable functional/prefer-readonly-type */` => `/* eslint-disable functional/prefer-immutable-types, functional/type-declaration-immutability */`
- Added `ignoreInferredTypes: true` option

Now I am down to 940 problems! Will pick an example of the remaining ones and post.

**Comment by jonaskello** [comment]
One of the most common cases seems to be this:

```ts
// The Foo type comes from an external library where it is delcared like this
type Foo = { hello: string };

// Parameter should have an immutability of at least "ReadonlyShallow" (actual: "Mutable"). eslint functional/prefer-immutable-types
export function foo(bar: Foo): string {
  return "";
}
```

I think that is 100% correct but is is not compatible with how the old rule worked. Did you mean that `ignoreInferredTypes` should have an effect on this case? The settings I currently use are this:

```js
  rules: {
    // "functional/prefer-readonly-type": ["error", { allowLocalMutation: true, ignorePattern: "^[mM]utable" }],
    "functional/prefer-immutable-types": [
      "error",
      {
        enforcement: "ReadonlyShallow",
        variables: { ignoreInFunctions: true, ignoreInferredTypes: true },
        parameters: { ignoreInferredTypes: true, ignoreInferredTypes: true },
        returnTypes: { ignoreInferredTypes: true, ignoreInferredTypes: true },
      },
    ],
    "functional/type-declaration-immutability": [
      "error",
      { rules: [{ identifiers: "^(?!I?Mutable).+", immutability: "ReadonlyShallow" }] },
    ],
  },
```

**Comment by RebeccaStevens** [comment]
So that is one of the cases where you would need to use a utility type to wrap `Foo` to make it immutable.

[type-fest](https://github.com/sindresorhus/type-fest)'s `ReadonlyDeep` is one such type that can be used to achieve this.

Otherwise, you'll need to just turn off the rule for that case.

**Comment by jonaskello** [comment]
> Otherwise, you'll need to just turn off the rule for that case.

To be compatible with the old rule we would have to support turn the rule off for just `Foo` but not `Array<string>` which I think is not currently possible? (and perhaps should not be possible, this is just for backwards combability)

```ts
// The Foo type comes from an external library where it is delcared like this
type Foo = { hello: string };

// Can we warn only on Array<string> but not on Foo ?
export function foo(bar: Foo, baz: Array<string>): string {
  return "";
}
```

**Comment by jonaskello** [comment]
Yes, that would of course be one way to migrate. Since `prefer-readonly-type` as it is being deprecated and I think many of the projects that use this package uses that rule I think we should provide guidance/docs how to migrate the with as little friction as possible. So to start that off I now have the following info from my attempts at migration:

Settings that are as close as you can get to `prefer-readonly-type`:

```js
  rules: {
    // "functional/prefer-readonly-type": ["error", { allowLocalMutation: true, ignorePattern: "^[mM]utable" }],
    "functional/prefer-immutable-types": [
      "error",
      {
        enforcement: "ReadonlyShallow",
        ignoreInferredTypes: true,
        variables: { ignoreInFunctions: true },
        parameters: { ignoreInferredTypes: true },
        returnTypes: { ignoreInferredTypes: true },
      },
    ],
    "functional/type-declaration-immutability": [
      "error",
      { rules: [{ identifiers: "^(?!I?Mutable).+", immutability: "ReadonlyShallow" }] },
    ],
  },
```

In addition the advice for migrators would be to:

- Replace `/* eslint-disable functional/prefer-readonly-type */` with `/* eslint-disable functional/prefer-immutable-types, functional/type-declaration-immutability */`
- For parameters that previously was not detected (such as types coming from external sources without readonly attributes).
  - Add ignore comment for them.
  - Or use a mapped type to make them readonly, the built-in `Readonly<T>` should work for shallow cases (I think?)
 
Anything else that is possible to do in order do minimize migration friction?

**Comment by jonaskello** [comment]
For the case of `Foo` above it works to just wrap it with `Readonly<Foo>` since the settings are `ReadonlyShallow`. Would it be possible to make an auto-fixer for this case? Then migration would be easier as you can just run `eslint --fix` to migrate.

**Comment by RebeccaStevens** [comment]
Yeah, if everything else is sorted now, I can start working on a fixer.

**Comment by RebeccaStevens** [comment]
@jonaskello I've finally gotten around to setup that fixer.
The fixer will work out of the box for the `ReadonlyShallow` enforcement level.
The `fixer` option need to be used to configure the fixer for higher enforcement levels.

It should now be release in beta 13. Let me know if you find any issues with it.

**Comment by jonaskello** [comment]
Btw, I must say the new rule is much more comprehensive than the old one, which is great :-). While testing the new rule it helped me find a bug in a code generator that should generate fully readonly types (see [this PR](https://github.com/stephenh/ts-proto/pull/706)).

**Comment by RebeccaStevens** [comment]
Just released beta 14 which should resolve the issues with arrays, sets and maps.

I don't think we can really support fixing to this:

```ts
export type Foo = {
  readonly bar: string;
  readonly baz: string;
};
```

The reason being that with the way we are now analyzing type immutability, we don't know where the violations are happening within the type, just that there is at least one violation. We could maybe get this to work for shallowly readonly enforcement when the type is simple, but I think it would be better to use a different rule (new rule?) to enforce this stylistic requirement. [`@typescript-eslint/array-type`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/array-type.md) does this for arrays.

**Comment by RebeccaStevens** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/6004

**Comment by jonaskello** [comment]
I can see how that is different now that the whole type is checked rather than checking for readonly annotations. I agree that a stylistic rule would make sense here. 

The only downside to that would be that you may have to run two fixes to get to the desired end result, one for adding the `Readonly<T>` wrapper and one more for changing that into `readonly` modifiers. (Not totally sure that would be the case though). However I think that would be a fair trade-off for having the comprehensiveness of the new rule.

**Comment by jonaskello** [comment]
I ran `eslint --fix` to migrate/test a codebase and it worked, basically it wrapped everything in `Readonly<T>`. The one problem that I came across was that it wrapped function types which lead to some compile errors after fixing that I'm not really sure how to deal with. Here is an example:

```ts
interface Props {
  readonly title: string;
}

export const Icons: Readonly<React.FC<Props>> = () => {
  <div/>
};
```

I haven't had time to investigate exactly what is going on yet.

Wrapping `React.FC<Props>` lead to the compile error: 
```
Type '() => Element' has no properties in common with type 'Readonly<FC<Props>>'.ts(2559)
```

Here is the definition of `React.FC`.

```ts
    type FC<P = {}> = FunctionComponent<P>;

    interface FunctionComponent<P = {}> {
        (props: P, context?: any): ReactElement<any, any> | null;
        propTypes?: WeakValidationMap<P> | undefined;
        contextTypes?: ValidationMap<any> | undefined;
        defaultProps?: Partial<P> | undefined;
        displayName?: string | undefined;
    }
```

**Comment by RebeccaStevens** [comment]
That's a good find. I'll see if sort that.

**Comment by RebeccaStevens** [comment]
So I'm not sure why exactly TypeScript is complaining about that case.
From what I've read online though, the use of `React.FC` is discourage. Instead, it's recommended to use the types more directly:

```ts
const Element = (props: Props) => (
  <div/>
);
```

Alternatively, `React.FC` could just be marked as readonly or ignored via settings/options.

**Comment by RebeccaStevens** [comment]
@jonaskello Just released a new version with that new rule (`readonly-type`). It's not enabled by default.

**Comment by jonaskello** [comment]
I did some more digging into the pervious case with the function. Trying in a more general (non-react) example:

```ts
interface AnExternalFunctionType {
  (a: string): string;
  extraProperty: string | undefined;
}

export const Icons: AnExternalFunctionType = () => {
  return "";
};
```

In this case the problem is that the `extraProperty` does not have an `readonly`  modifier so the rule will complain on the usage when defining the function. In this code I could add the `readonly` attribute because the interface is in the same file but if it was defined externally I could not. Anyway what the fixer does is to wrap with `Readonly` so it becomes `Readonly<AnExternalFunctionType>`.  However since `Readonly<T>` is a mapped type it will map all properties with readonly modifiers (like `extraProperty`) but it will not map the call signature. So when the type is mapped the call signature is lost (at least that what was I understood from this [SO question](https://stackoverflow.com/questions/59827113/call-readonly-function-in-typescript/59827399#59827399)).

Not sure what to do about it but at least I think that explains what is going on :-).

**Comment by jonaskello** [comment]
Nice, I'll take a look at the new `readonly-type` rule!

**Comment by jonaskello** [comment]
Following up on the previous example with the function above. Interestingly the following code passes the linter and also seems to compile:

```ts
export const Icons: Readonly<AnExternalFunctionType> & AnExternalFunctionType = () => {
  return "";
};
```

**Comment by jonaskello** [comment]
I activated the `readonly-type` rule but I'm not sure I have the correct config to use it for the case I had in mind. 
Just to clarify, the most common use case I have for the old fixer is shown in the clip below. Is there some config I could use to have the same effect with the new rules?

https://user-images.githubusercontent.com/664076/204089583-28b2f432-8f36-4f48-a8dd-710e6de2cf24.mp4

**Comment by RebeccaStevens** [comment]
`type-declaration-immutability` is the rule that would flag that type as it is an alias. That rule doesn't currently have a fixer.

The new rule `readonly-type` is designed only to work on types that are already readonly.
If you configure the rule as `functional/readonly-type: ["error", "keyword"]`, then the following will be auto-fixed:

from:

```ts
type Foo = Readonly<{
  bar: string;
  baz: string;
}>;
```

to:

```ts
type Foo = {
  readonly bar: string;
  readonly baz: string;
};
```

**Comment by jonaskello** [comment]
Aha, yeah that makes sense. So what would be needed to have similar behavior as the old rule is a fixer for `type-declaration-immutability` that wraps it with `Readonly<T>` and then after that the  `readonly-type` rule would be able to transform it to `readonly` modifiers? Or would the `type-declaration-immutability` rule directly make it into `readonly` modifiers?

**Comment by RebeccaStevens** [comment]
Yes, `type-declaration-immutability` would wraps it with Readonly<T> which `readonly-type` will then transform it to readonly modifiers

**Comment by RebeccaStevens** [comment]
I think all that's left to do with this is:

- [ ] add a fixer for `type-declaration-immutability`
- [ ] fix issues with ignoring by name pattern

**Comment by RebeccaStevens** [comment]
@jonaskello I finally got around to making that fixer. I think everything for this PR is done now.
I'll start drafting the release notes.

Let me know if you find any errors or any other reason not release. Otherwise, I'll probably release it sometime in the next week.

**Comment by RebeccaStevens** [comment]
@jonaskello Are you all good with me adding a donation link?

**Comment by jonaskello** [comment]
> @jonaskello Are you all good with me adding a donation link?

Yes, totally OK with me

**Comment by jonaskello** [comment]
I noticed  `prefer-immutable-types` fixes `string[]` into `Readonly<string[]>`. Perhaps fixing it into `readonly string[]` would be better? 

It does already fix `Array<string>` into `ReadonlyArray<string>` which is good.

**Comment by jonaskello** [comment]
I'm trying to test the `type-declaration-immutability` fixer but I cannot make the fixer option appear in vscode. 

In my [test repo](https://github.com/jonaskello/eslint-functional-test) I'm getting a `type-declaration-immutability` lint error on [this line](https://github.com/jonaskello/eslint-functional-test/blob/6203c7a9e6fbe4433907431d8d1aefb9521d2d0b/src/test1.ts#L1). However the fixer option is not availalbe. Would this be a case that can be fixed by the new fixer?

image

**Comment by RebeccaStevens** [comment]
> I'm trying to test the `type-declaration-immutability` fixer but I cannot make the fixer option appear in vscode.

By default, the fixer is disabled for the `type-declaration-immutability`. This is because in the general case, we can't determine how to make a type comply with the rule.

The `recommended` and `lite` rulesets configure the rule with a fixer some contexts but not all.

Try this config to get the fixer working for your setup:

```json
"functional/type-declaration-immutability": [
  "error",
  {
    rules: [{ identifiers: "^(?!I?Mutable).+", immutability: "ReadonlyShallow" }],
    fixer: [
      { pattern: "^(Array|Map|Set)<(.+)>$", replace: "Readonly$1<$2>" },
      { pattern: "^(.+)$", replace: "Readonly<$1>" },
    ],
  }
]
```

**Comment by RebeccaStevens** [comment]
> I noticed `prefer-immutable-types` fixes `string[]` into `Readonly<string[]>`. Perhaps fixing it into `readonly string[]` would be better?

I might be able to get that working but I'm not sure about in the non-simple case (as I have to select it with a `RegExp`) e.g. `(string | { complex: ({ structure: "that"; } | { "is": "hard", "to": "support" }) })[]`

**Comment by RebeccaStevens** [comment]
Here's the [v5 release notes (draft)](https://github.com/eslint-functional/eslint-plugin-functional/releases/tag/untagged-293019dbe3f27acc6aa6) if you want to check it out.

**Comment by jonaskello** [comment]
> By default, the fixer is disabled for the type-declaration-immutability

Aha, my bad, I did not check the docs :-). Got it working now! 

I noticed the code got formatted to one line when applying the fix, is this something that the fixer is doing? If so would it be possible to have it keep the original multi-line formatting? See screencapture below:


https://user-images.githubusercontent.com/664076/215168863-faa2745b-be13-49b5-9ee1-d35944d9de8f.mp4

**Comment by jonaskello** [comment]
> Here's the [v5 release notes (draft)](https://github.com/eslint-functional/eslint-plugin-functional/releases/tag/untagged-293019dbe3f27acc6aa6) if you want to check it out.

I think you've done a bunch of good work here, and if you're ready to release it then I say go for it :-)

Whatever is left (like the formatting I mentioned above) I think could be done in separate issues after the release.

**Comment by RebeccaStevens** [comment]
The formatting issue should hopefully be fixed now.

**Pull request merged**
